name: Python CI

#Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
     - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #set up python environment
      - name: check out code
        uses: actions/checkout@v2
        with:
          python-version: '3.8' 
      # Install dependencies
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #Run tests
      - name: Run tests
        run: pytest   
    

    
